/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solicitudes_consejo_de_facultad;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import java.sql.*; 
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author usuario
 */
public class Homologacion extends javax.swing.JFrame {
    ArrayList<MateriaV> list = new ArrayList<MateriaV>();
    ArrayList<Object> listUdem = new ArrayList<Object>();
    ArrayList<Double> notas = new ArrayList<Double>();
    
    /**
     * Creates new form Homologacion
     */

    public Homologacion() throws Exception{
        initComponents();
        jComboBox2.removeAllItems();
        String sql="SELECT NOMBRE FROM MATERIA";
        DefaultComboBoxModel md1 = new DefaultComboBoxModel(BD.leerDatosV(sql));
        jComboBox2.setModel(md1);    
    }

    public void agregar(){
    DefaultListModel lista = new DefaultListModel();
    DefaultListModel listaUdem = new DefaultListModel();
    String nombre;
    Object nombreU;
    nombre = mvistas_hmaterias.getText();
    nombreU = jComboBox2.getSelectedItem();
    MateriaV m = new MateriaV(nombre);
    list.add(m);
    listUdem.add(nombreU);
        for (int i = 0; i < list.size(); i++) {
            lista.addElement(list.get(i));
            listaUdem.addElement(listUdem.get(i));
            notas.add(Double.parseDouble(nota_hmaterias.getText()));
        }
    list_mvistas.setModel(lista);
    list_mudem.setModel(listaUdem);
    mvistas_hmaterias.setText("");
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ced_hmaterias = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cod_hmaterias = new javax.swing.JTextField();
        fechaE_hmaterias = new javax.swing.JTextField();
        fechaR_hmaterias = new javax.swing.JTextField();
        prog_hmaterias = new javax.swing.JTextField();
        semestre_hmaterias = new javax.swing.JTextField();
        uproce_hmaterias = new javax.swing.JTextField();
        rad_hmaterias = new javax.swing.JTextField();
        rec_hmaterias = new javax.swing.JTextField();
        numasi_hmaterias = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnVistaprevia_hmaterias = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_mvistas = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        list_mudem = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        mvistas_hmaterias = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nota_hmaterias = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        nom_homo = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        valor_homo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Solicitud de homologación de materias");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(794, 0, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel6.setText("Código:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        ced_hmaterias.setName("ced_hmaterias"); // NOI18N
        getContentPane().add(ced_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 100, -1));

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel7.setText("Nombre:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel8.setText("Fecha de expedición:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel9.setText("Fecha de respuesta (CAD):");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel10.setText("Valor:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        cod_hmaterias.setName("cod_hmaterias"); // NOI18N
        getContentPane().add(cod_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 100, -1));

        fechaE_hmaterias.setName("fechaE_hmaterias"); // NOI18N
        fechaE_hmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaE_hmateriasActionPerformed(evt);
            }
        });
        getContentPane().add(fechaE_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 100, -1));

        fechaR_hmaterias.setName("fechaR_hmaterias"); // NOI18N
        getContentPane().add(fechaR_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 100, -1));

        prog_hmaterias.setName("prog_hmaterias"); // NOI18N
        getContentPane().add(prog_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 100, -1));

        semestre_hmaterias.setName("semestre_hmaterias"); // NOI18N
        getContentPane().add(semestre_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, 100, -1));

        uproce_hmaterias.setName("uproce_hmaterias"); // NOI18N
        getContentPane().add(uproce_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 100, -1));

        rad_hmaterias.setName("rad_hmaterias"); // NOI18N
        getContentPane().add(rad_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 100, -1));

        rec_hmaterias.setName("rec_hmaterias"); // NOI18N
        getContentPane().add(rec_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 100, -1));

        numasi_hmaterias.setName("numasi_hmaterias"); // NOI18N
        getContentPane().add(numasi_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 250, 100, -1));

        jLabel11.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel11.setText("Universidad de procedencia:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel12.setText("Semestre:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel13.setText("Número de radicado: ");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel14.setText("Número de caja:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel15.setText("Número de asignaturas reconocidas:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.setName("btnguardar_hmaterias"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, 90, 30));

        btnVistaprevia_hmaterias.setBackground(new java.awt.Color(255, 51, 51));
        btnVistaprevia_hmaterias.setForeground(new java.awt.Color(240, 240, 240));
        btnVistaprevia_hmaterias.setText("Vista Previa");
        btnVistaprevia_hmaterias.setName("btnVistaprevia_hmaterias"); // NOI18N
        btnVistaprevia_hmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVistaprevia_hmateriasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVistaprevia_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 520, 110, 30));

        list_mvistas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        list_mvistas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_mvistas.setName("list_mvistas"); // NOI18N
        jScrollPane1.setViewportView(list_mvistas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 220, 100));

        list_mudem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        list_mudem.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_mudem.setName("list_mudem"); // NOI18N
        jScrollPane2.setViewportView(list_mudem);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 210, 100));

        jLabel16.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel16.setText("Materias Universidad de Medellín");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel17.setText("Materias Universidad procedencia");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jLabel18.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel18.setText("Materias universidad de procedencia:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 220, -1));

        mvistas_hmaterias.setName("mvistas_hmaterias"); // NOI18N
        getContentPane().add(mvistas_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 190, -1));

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Agregar");
        jButton4.setName("btnagregar_hmaterias"); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(90, 30));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, -1, -1));

        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jLabel19.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel19.setText("Materia Universidad de Medellín:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabel20.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel20.setText("Nota:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, -1, -1));

        nota_hmaterias.setName("nota_hmaterias"); // NOI18N
        nota_hmaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota_hmateriasActionPerformed(evt);
            }
        });
        getContentPane().add(nota_hmaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 70, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 940, 10));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("*");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 10, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 0, 0));
        jLabel22.setText("*");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 10, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("*");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 10, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setText("*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 10, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 0, 0));
        jLabel25.setText("*");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 10, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 0, 0));
        jLabel26.setText("*");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 10, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 0));
        jLabel27.setText("*");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 10, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 0, 0));
        jLabel28.setText("*");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 130, 10, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 0, 0));
        jLabel29.setText("*");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 10, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 0, 0));
        jLabel30.setText("*");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 10, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 0, 0));
        jLabel31.setText("*");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, 10, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 0, 0));
        jLabel32.setText("*");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 0, 0));
        jLabel33.setText("*");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 10, -1));
        getContentPane().add(nom_homo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 100, -1));

        jLabel34.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel34.setText("Cédula:");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 0, 0));
        jLabel35.setText("*");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 10, -1));

        jLabel36.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel36.setText("Programa:");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 0, 0));
        jLabel37.setText("*");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 10, -1));
        getContentPane().add(valor_homo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 100, -1));

        jLabel2.setText("Campos obligatorios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 0, 0));
        jLabel38.setText("*");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 10, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                if (cod_hmaterias.getText().isEmpty() || fechaE_hmaterias.getText().isEmpty() || ced_hmaterias.getText().isEmpty() || uproce_hmaterias.getText().isEmpty() || rad_hmaterias.getText().isEmpty() || rec_hmaterias.getText().isEmpty() || numasi_hmaterias.getText().isEmpty() || semestre_hmaterias.getText().isEmpty() || prog_hmaterias.getText().isEmpty() || fechaR_hmaterias.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan campos por ingresar");
        } else {
            try {
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                cal.setTime(sdf.parse(fechaE_hmaterias.getText()));
                java.sql.Date sqlDate = new java.sql.Date(cal.getTimeInMillis());
                if(cod_hmaterias.getText().isEmpty() || fechaE_hmaterias.getText().isEmpty() || ced_hmaterias.getText().isEmpty() || uproce_hmaterias.getText().isEmpty() || rad_hmaterias.getText().isEmpty() || rec_hmaterias.getText().isEmpty() || numasi_hmaterias.getText().isEmpty() || semestre_hmaterias.getText().isEmpty() || prog_hmaterias.getText().isEmpty() || fechaR_hmaterias.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Todos los Campos son requeridos");
                }else{
                    BD.agregarHomologacion(Integer.parseInt(cod_hmaterias.getText()),sqlDate,Integer.parseInt(ced_hmaterias.getText()), uproce_hmaterias.getText(), Integer.parseInt(rad_hmaterias.getText()), Integer.parseInt(rec_hmaterias.getText()), Integer.parseInt(numasi_hmaterias.getText()), semestre_hmaterias.getText(), prog_hmaterias.getText(),fechaR_hmaterias.getText());
                    for (int i = 0; i < list.size(); i++) {
                        BD.agregarMhomologacion(Integer.parseInt(cod_hmaterias.getText()),list.get(i).toString(), listUdem.get(i).toString(),notas.get(i),Integer.parseInt(cod_hmaterias.getText()));
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"Error Homologacion:"+e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (mvistas_hmaterias.getText().isEmpty() && nota_hmaterias.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite la materia y su respectiva nota porfavor");
        } else {
            agregar();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnVistaprevia_hmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVistaprevia_hmateriasActionPerformed
        // TODO add your handling code here:
        if (cod_hmaterias.getText().isEmpty() || fechaE_hmaterias.getText().isEmpty() || ced_hmaterias.getText().isEmpty() || uproce_hmaterias.getText().isEmpty() || rad_hmaterias.getText().isEmpty() || rec_hmaterias.getText().isEmpty() || numasi_hmaterias.getText().isEmpty() || semestre_hmaterias.getText().isEmpty() || prog_hmaterias.getText().isEmpty() || fechaR_hmaterias.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan campos para generar el documento");
        } else {
            try {
                Homologacion le = new Homologacion();
                DocHomologaciones dle = new DocHomologaciones(le,"Daniel Sanchez Perez",nom_homo.getText(),prog_hmaterias.getText(),valor_homo.getText(),semestre_hmaterias.getText(),
                fechaE_hmaterias.getText(),rec_hmaterias.getText(),numasi_hmaterias.getText(),rad_hmaterias.getText(),uproce_hmaterias.getText());
                dle.openDoc();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al generar el documento: "+e);
            }
        }
        
    }//GEN-LAST:event_btnVistaprevia_hmateriasActionPerformed

    private void nota_hmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota_hmateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota_hmateriasActionPerformed

    private void fechaE_hmateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaE_hmateriasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaE_hmateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homologacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homologacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homologacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homologacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Homologacion().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(Homologacion.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVistaprevia_hmaterias;
    public javax.swing.JTextField ced_hmaterias;
    private javax.swing.JTextField cod_hmaterias;
    public javax.swing.JTextField fechaE_hmaterias;
    public javax.swing.JTextField fechaR_hmaterias;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JList<String> list_mudem;
    public javax.swing.JList<String> list_mvistas;
    public javax.swing.JTextField mvistas_hmaterias;
    public javax.swing.JTextField nom_homo;
    public javax.swing.JTextField nota_hmaterias;
    public javax.swing.JTextField numasi_hmaterias;
    public javax.swing.JTextField prog_hmaterias;
    public javax.swing.JTextField rad_hmaterias;
    public javax.swing.JTextField rec_hmaterias;
    public javax.swing.JTextField semestre_hmaterias;
    public javax.swing.JTextField uproce_hmaterias;
    public javax.swing.JTextField valor_homo;
    // End of variables declaration//GEN-END:variables
}
