/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solicitudes_consejo_de_facultad;

import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.synth.ColorType;

/**
 *
 * @author usuario
 */
public class Linea_enfasis extends javax.swing.JFrame {
ArrayList<String> estado = new ArrayList<String>();
    /**
     * Creates new form Index
     */
    public Linea_enfasis() {
        initComponents();
        estado.add("Aprobado");
        estado.add("Desaprobado");
        for (int i = 0; i < estado.size(); i++) {
            estado_enfasis.addItem(estado.get(i));
        }
        jProgramas.removeAllItems();
        String sql="SELECT NOM_PROGRAMA FROM PROGRAMA";
        DefaultComboBoxModel md1 = new DefaultComboBoxModel(BD.leerDatosV(sql));
        jProgramas.setModel(md1);
        //this.getContentPane().setBackground(Color.white);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ced_enfasis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rad_enfasis = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        asi_enfasis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        esp_enfasis = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        materia_enfasis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        fecha_enfasis = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btn_generarEnfasis = new javax.swing.JButton();
        btn_guardarEnfasis = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        estado_enfasis = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jProgramas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(900, 589));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel1.setText("Cédula:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        ced_enfasis.setName("ced_enfasis"); // NOI18N
        getContentPane().add(ced_enfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 146, -1));

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel3.setText("Programa:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel4.setText("Número del radicado:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        rad_enfasis.setName("rad_enfasis"); // NOI18N
        getContentPane().add(rad_enfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 146, -1));

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel5.setText("Código asignatura:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        asi_enfasis.setName("asi_enfasis"); // NOI18N
        getContentPane().add(asi_enfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 141, 146, -1));

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel6.setText("Código especializacion:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 194, -1, -1));

        esp_enfasis.setName("esp_enfasis"); // NOI18N
        getContentPane().add(esp_enfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 194, 146, -1));

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel7.setText("Línea de énfasis");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 247, -1, -1));

        materia_enfasis.setName("materia_enfasis"); // NOI18N
        getContentPane().add(materia_enfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 247, 146, -1));

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel8.setText("Fecha reunion:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, -1, -1));

        fecha_enfasis.setName("fecha_enfasis"); // NOI18N
        getContentPane().add(fecha_enfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 146, -1));

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 0, 13)); // NOI18N
        jLabel9.setText("Estado:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        btn_generarEnfasis.setBackground(new java.awt.Color(255, 51, 51));
        btn_generarEnfasis.setForeground(new java.awt.Color(255, 255, 255));
        btn_generarEnfasis.setLabel("Generar Documento");
        btn_generarEnfasis.setName("btn_generarEnfasis"); // NOI18N
        btn_generarEnfasis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarEnfasisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_generarEnfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));

        btn_guardarEnfasis.setBackground(new java.awt.Color(255, 51, 51));
        btn_guardarEnfasis.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardarEnfasis.setLabel("Guardar");
        btn_guardarEnfasis.setName("btn_guardarEnfasis"); // NOI18N
        btn_guardarEnfasis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarEnfasisActionPerformed(evt);
            }
        });
        getContentPane().add(btn_guardarEnfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 82, -1));

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("Solicitud de cambio de línea de énfasis. ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(879, 0, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("*");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 0, 0));
        jLabel15.setText("*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 0, 0));
        jLabel16.setText("*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 0, 0));
        jLabel17.setText("*");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 0, 0));
        jLabel19.setText("*");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 195, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 0));
        jLabel20.setText("*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 0, 0));
        jLabel21.setText("*");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        estado_enfasis.setName("estado_enfasis"); // NOI18N
        getContentPane().add(estado_enfasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, -1, -1));

        jLabel23.setText("Campos obligatorios");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 0));
        jLabel24.setText("*");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        getContentPane().add(jProgramas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarEnfasisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarEnfasisActionPerformed
        // TODO add your handling code here:
        if(ced_enfasis.getText().isEmpty() && rad_enfasis.getText().isEmpty() && asi_enfasis.getText().isEmpty() && esp_enfasis.getText().isEmpty() && materia_enfasis.getText().isEmpty() && fecha_enfasis.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Faltan campos por ingresar");
        }else{        
            try {
                Calendar cal = Calendar.getInstance();
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                cal.setTime(sdf.parse(fecha_enfasis.getText()));
                java.sql.Date sqlDate = new java.sql.Date(cal.getTimeInMillis());
                if(ced_enfasis.getText().isEmpty() && rad_enfasis.getText().isEmpty() && asi_enfasis.getText().isEmpty() && esp_enfasis.getText().isEmpty() && materia_enfasis.getText().isEmpty() && fecha_enfasis.getText().isEmpty()){
                    JOptionPane.showMessageDialog(null,"Algunos Campos Estan Vacios");
                }else{
                    try {
                        BD.agregar_C_Enfasis(Integer.parseInt(ced_enfasis.getText()), Integer.parseInt(rad_enfasis.getText()), Integer.parseInt(asi_enfasis.getText()), Integer.parseInt(esp_enfasis.getText()), Integer.parseInt(materia_enfasis.getText()),sqlDate, estado_enfasis.getSelectedItem().toString(),Integer.parseInt(jProgramas.getSelectedItem().toString()));
                    } catch (Exception e) {
                        e.getMessage();
                    }
                }
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null,"Error en la Fecha"+ex);
            }
        }
    }//GEN-LAST:event_btn_guardarEnfasisActionPerformed

    private void btn_generarEnfasisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarEnfasisActionPerformed
    Linea_enfasis le = new Linea_enfasis();
    try {
            if (ced_enfasis.getText().isEmpty() || rad_enfasis.getText().isEmpty() || esp_enfasis.getText().isEmpty() || materia_enfasis.getText().isEmpty() || asi_enfasis.getText().isEmpty() || fecha_enfasis.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Algún campo esta vacio");
        } else {
            if (BD.nombreLineaEnfasis(ced_enfasis.getText()).isEmpty() ||rad_enfasis.getText().isEmpty() ||BD.nombreEspecializacion(esp_enfasis.getText()).isEmpty() || BD.nombreEnfasis(materia_enfasis.getText()).isEmpty() || rad_enfasis.getText().isEmpty() || BD.nombreMateria(asi_enfasis.getText()).isEmpty()) {
                JOptionPane.showMessageDialog(null, "Algun dato Ingresado no existe");
            }else{
                DocLineaEnfasis dle = new DocLineaEnfasis(le,ced_enfasis.getText(),BD.nombreEspecializacion(esp_enfasis.getText()),estado_enfasis.getSelectedItem().toString(),fecha_enfasis.getText(),BD.nombreEnfasis(materia_enfasis.getText()),BD.nombreLineaEnfasis(ced_enfasis.getText()),jProgramas.getSelectedItem().toString(),rad_enfasis.getText(),BD.nombreMateria(asi_enfasis.getText()));
                dle.openDoc();
            }
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo generar el documento");
        }
    }//GEN-LAST:event_btn_generarEnfasisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField asi_enfasis;
    private javax.swing.JButton btn_generarEnfasis;
    private javax.swing.JButton btn_guardarEnfasis;
    public javax.swing.JTextField ced_enfasis;
    public javax.swing.JTextField esp_enfasis;
    public javax.swing.JComboBox<String> estado_enfasis;
    public javax.swing.JTextField fecha_enfasis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> jProgramas;
    public javax.swing.JTextField materia_enfasis;
    public javax.swing.JTextField rad_enfasis;
    // End of variables declaration//GEN-END:variables
}
