/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package solicitudes_consejo_de_facultad;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author usuario
 */
public class Menu extends javax.swing.JFrame {
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        P_logo log = new P_logo();
        jPanel1.add(log, new org.netbeans.lib.awtextra.AbsoluteConstraints(02, 02, 02, 02));
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtHomo = new javax.swing.JLabel();
        txtLinea = new javax.swing.JLabel();
        txtRepor = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAyuda = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(100, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(186, 15, 22));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 110));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtHomo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homologacion.png"))); // NOI18N
        txtHomo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHomoMouseClicked(evt);
            }
        });
        jPanel3.add(txtHomo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txtLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linea_enfasis.png"))); // NOI18N
        txtLinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLineaMouseClicked(evt);
            }
        });
        jPanel3.add(txtLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        txtRepor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        txtRepor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtReporMouseClicked(evt);
            }
        });
        jPanel3.add(txtRepor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Homologacíon ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Línea de énfasis");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Reportes");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        txtAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ayuda.png"))); // NOI18N
        txtAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAyudaMouseClicked(evt);
            }
        });
        jPanel3.add(txtAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Ayuda");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 570));

        jPanel1.setMaximumSize(new java.awt.Dimension(1090, 1080));
        jPanel1.setMinimumSize(new java.awt.Dimension(1090, 1080));
        jPanel1.setPreferredSize(new java.awt.Dimension(1090, 1080));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 1040, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHomoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHomoMouseClicked
        try {
            Homologacion h;
            h = new Homologacion();
            jPanel1.removeAll();
            jPanel1.add(h.getContentPane(), new org.netbeans.lib.awtextra.AbsoluteConstraints(02, 02, 02, 02));
            pack();
        } catch (Exception ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtHomoMouseClicked

    private void txtLineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLineaMouseClicked
        // TODO add your handling code here:
        try {
            Linea_enfasis l = new Linea_enfasis();
            jPanel1.removeAll();
            jPanel1.add(l.getContentPane(), new org.netbeans.lib.awtextra.AbsoluteConstraints(02, 02, 02, 02));
            pack();
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_txtLineaMouseClicked

    private void txtReporMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtReporMouseClicked
        try {
            // TODO add your handling code here:
            Reporte rh = new Reporte();
            jPanel1.removeAll();
            jPanel1.add(rh.getContentPane(), new org.netbeans.lib.awtextra.AbsoluteConstraints(02, 02, 02, 02));
            pack();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_txtReporMouseClicked

    private void txtAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAyudaMouseClicked
        // TODO add your handling code here:
        AyudaPanel help = new AyudaPanel();
        jPanel1.removeAll();
        jPanel1.add(help);
        pack();
    }//GEN-LAST:event_txtAyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel txtAyuda;
    private javax.swing.JLabel txtHomo;
    private javax.swing.JLabel txtLinea;
    private javax.swing.JLabel txtRepor;
    // End of variables declaration//GEN-END:variables

    private void add(String EAST) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
